#!/bin/bash

# Author  : ONJANIAINA Henintsoa Stephana
# Created : 23/03/24 17:34:12
# Repo : henintsoa98/dotfiles.debian12
# File : CONFIG/CUSTOMRC

source /usr/local/bin/color
clear -x
# POWERLEVEL SETUP
[ -f "~/.p10k.zsh" ] && (InsProm=$(cat ~/.zshrc | grep p10k-instant-prompt);if [[ "$InsProm" ]];then sed -i "1,7d" ~/.zshrc;fi;sed -i "s/# battery/battery/;s%  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}%# typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}%;s%typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2%typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=7%;s%typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=0%typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=4%;s%typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2%typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=7%;s%typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0%typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=4%" ~/.p10k.zsh)

alias ping8="ping 8.8.8.8"
alias bye="/sbin/poweroff"
alias clear="clear -T xterm"
alias vim="TERM=xterm-256color vim"
alias wq="exit"
alias "wq!"="/sbin/poweroff"

github1()
{
	if [[ "$1" ]]; then
		git clone --depth 1 https://github.com/$1
		REPO=$(echo $1 | sed "s#/# #" |awk '{print $2}')
		tar -cJf ${REPO}_master.tar.xz $REPO
	else
		echo "Usage with user/repo : github1 henintsoa98/resume"
	fi
}
github0()
{
	if [[ "$1" ]]; then
		git clone https://github.com/$1
		REPO=$(echo $1 | sed "s#/# #" |awk '{print $2}')
		tar -cJf ${REPO}.tar.xz $REPO

	else
		echo "Usage with user/repo : github0 henintsoa98/resume"
	fi
}
mytmate()
{
	tmate -S /tmp/tmate.sock new-session -d
	tmate -S /tmp/tmate.sock wait tmate-ready
	tmate -S /tmp/tmate.sock display -p "#{tmate_ssh}"
	if [[ "$1" ]]; then
		tmate -S /tmp/tmate.sock display -p "#{tmate_ssh}"
	fi
}

zsh_switch_theme()
{
	IS_POWERLEVEL10K=$(grep "powerlevel10k" $HOME/.zshrc)
	if [[ "IS_POWERLEVEL10K" ]] ; then
		sed -i 's#ZSH_THEME="powerlevel10k/powerlevel10k"#ZSH_THEME="bureau-henintsoa"#' $HOME/.zshrc
	else
		sed -i 's#ZSH_THEME="bureau-henintsoa"#ZSH_THEME="powerlevel10k/powerlevel10k"#' $HOME/.zshrc
	fi
	zsh
}

TIMER_FORMAT='[%d]';

if [[ "$TTY" == "/dev/tty1" ]]; then
        Hyprland
	# tmux
fi

_HELLOWORD="#> hello <# .henintsoa. _#]* 98 *[#_"
if [[ "$USER" == "root" ]]; then
	_HELLOWORD="\!\! WARNING \!\! > ROOT____.. ____USER #"
fi
figlet -f "ANSI Shadow" "$_HELLOWORD" | lolcat -a -d 10 -s 24000
